version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 9000:9000

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 9001
    volumes:
      - ./data:/app/data
      - ./images:/app/images